[project]
name = "atmod"
version = "0.1.0"
description = "Add a short description here"
authors = ["basknaake <bas.knaake@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]
install_e = "python -m pip install --no-deps --editable ."

[dependencies]
python = "3.11"
numpy = "<=1.24" # numba requirement
pandas = ">=2.0.1" 
pyarrow = "*"
pyproj = "*"
geopandas = "*"
openpyxl = "*"
shapely = ">=2.0.1" 
rasterio = "*"
xarray = "*"
rioxarray = "*"
dask = "*"
numba = "*"
owslib = "*"
netcdf4 = "*"
h5netcdf = "*"
matplotlib = "*"
black = "*"
pytest = "*"
pytest-cov = "*"
ruff = "*"
sphinx = "*"
sphinx-rtd-theme = "*"
pip = ">=24.0,<25"
ipykernel = ">=6.29.3,<6.30"
contextily = ">=1.5.2,<1.6"
